### ISSUE TITLE
项目clone下来启动不了

### ISSUE THREAD

**Issue by zhangyuexin** [payallmoney/wepy-echarts#1]

**Comment by payallmoney** [comment]
1, 下载https://github.com/ecomfe/echarts-for-weixin , 将 ec-canvas 和 pages 目录放入 native目录
 这个步骤你要做下
还要从echarts官网下载echarts.min.js 替换 ec-canvas 里面的 echarts.js

**Comment by payallmoney** [comment]
npm install wepy-cli -g
 cd wepy-echarts
 npm  install
 npm run dev 
这几个命令执行下

**Comment by payallmoney** [comment]
请提供错误信息
